config/routes.rb
Howedoin::Application.routes.draw do
  resources :txns, defaults: {format: :json}
  resources :accounts, defaults: {format: :json}
  get 'autofill' => 'txns#autofill'

end

app/models/txn.rb
class Txn < ActiveRecord::Base
  include HasEntered

  self.table_name = 'transaction'

  attr_accessible :date, :payee

  attr_accessor :num

  validates :date, presence: true

  belongs_to :payee, primary_key: 'payee_id'
  has_many :entries, foreign_key: 'trans_id', autosave: true
  has_one :posted_transaction

  def dup
    new_txn = super
    new_txn.entries = self.entries.map(&:dup)
    new_txn.entered = Time.now
    new_txn
  end

  def payee_name
    payee.name
  end

  def amount
    entries.joins(:account).where(account: { acct_type: ['asset', 'liability'] }).sum(:amount)
  end

  def pretty_print
    "#{date.strftime('%F')} \"#{payee.try(:name) || '<none>'}\" #{amount}\n" +
      entries.map(&:pretty_print).join("\n")
  end
end

app/controllers/txns_controller.rb
class TxnsController < ApplicationController
  # GET /txns
  # GET /txns.json
  def index
    @txns = Txn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @txns }
    end
  end

  # GET /txns/1
  # GET /txns/1.json
  def show
    @txn = Txn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @txn }
    end
  end

  def autofill
    if params[:payee] && params[:date]
      new_txn = Service::Autofill.from_last_payee_txn(params[:payee], params[:date])
    end
    respond_to do |format|
      format.json { render json: new_txn.to_json(:include => :entries) }
    end
  end

  # GET /txns/new
  # GET /txns/new.json
  def new
    @txn = Txn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @txn }
    end
  end

  # GET /txns/1/edit
  def edit
    @txn = Txn.find(params[:id])
  end

  # POST /txns
  # POST /txns.json
  def create
    @txn = Txn.new(params[:txn])

    respond_to do |format|
      if @txn.save
        format.html { redirect_to @txn, notice: 'Txn was successfully created.' }
        format.json { render json: @txn, status: :created, location: @txn }
      else
        format.html { render action: "new" }
        format.json { render json: @txn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /txns/1
  # PUT /txns/1.json
  def update
    @txn = Txn.find(params[:id])

    respond_to do |format|
      if @txn.update_attributes(params[:txn])
        format.html { redirect_to @txn, notice: 'Txn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @txn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /txns/1
  # DELETE /txns/1.json
  def destroy
    @txn = Txn.find(params[:id])
    @txn.destroy

    respond_to do |format|
      format.html { redirect_to txns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/txns_helper.rb
module TxnsHelper
end

app/views/txns/_form.html.erb
<%= form_for(@txn) do |f| %>
  <% if @txn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@txn.errors.count, "error") %> prohibited this txn from being saved:</h2>

      <ul>
      <% @txn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/txns/edit.html.erb
<h1>Editing txn</h1>

<%= render 'form' %>

<%= link_to 'Show', @txn %> |
<%= link_to 'Back', txns_path %>

app/views/txns/index.html.erb
<h1>Listing txns</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @txns.each do |txn| %>
  <tr>
    <td><%= link_to 'Show', txn %></td>
    <td><%= link_to 'Edit', edit_txn_path(txn) %></td>
    <td><%= link_to 'Destroy', txn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Txn', new_txn_path %>

app/views/txns/new.html.erb
<h1>New txn</h1>

<%= render 'form' %>

<%= link_to 'Back', txns_path %>

app/views/txns/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_txn_path(@txn) %> |
<%= link_to 'Back', txns_path %>