config/routes.rb
Howedoin::Application.routes.draw do
  resources :txns, defaults: {format: :json}
  resources :accounts, defaults: {format: :json}
  get 'autofill' => 'txns#autofill'

end

app/models/account.rb
class Account < ActiveRecord::Base
  include HasEntered

  self.table_name = 'account'

  attr_accessible :acct_type, :name, :number, :description, :opened_on, :closed, :closed_on, :payment_default, :stmt_amounts_negated

  has_many :statements, foreign_key: 'acct_id'

  # validates :acct_type, :inclusion 

  def self.payment_default
    Account.where(payment_default: true).first
  end

  def set_payment_default
    transaction do
      Account.payment_default.try { |a| a.update_attributes!(payment_default: false) }
      update_attributes!(payment_default: true)
    end
  end

  def asset?
    acct_type == 'asset'
  end

  def liability?
    acct_type == 'liability'
  end

  def asset_or_liability?
    asset? || liability?
  end

  def income?
    acct_type == 'income'
  end

  def expense?
    acct_type == 'expense'
  end

  def income_or_expense?
    income? || expense?
  end

  def stmt_amounts_negated?
    stmt_amounts_negated
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_area :number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :opened_on %><br />
    <%= f.date_select :opened_on %>
  </div>
  <div class="field">
    <%= f.label :closed %><br />
    <%= f.check_box :closed %>
  </div>
<!--
  <div class="field">
    <%= f.label :closed_on %><br />
    <%= f.date_select :closed_on %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Description</th>
    <th>Opened on</th>
    <th>Closed</th>
    <th>Closed on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= account.number %></td>
    <td><%= account.description %></td>
    <td><%= account.opened_on %></td>
    <td><%= account.closed %></td>
    <td><%= account.closed_on %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>

<p>
  <b>Number:</b>
  <%= @account.number %>
</p>

<p>
  <b>Description:</b>
  <%= @account.description %>
</p>

<p>
  <b>Opened on:</b>
  <%= @account.opened_on %>
</p>

<p>
  <b>Closed:</b>
  <%= @account.closed %>
</p>

<p>
  <b>Closed on:</b>
  <%= @account.closed_on %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>